### ISSUE TITLE
Hello,I met a bug: AttributeError: 'Trainer' object has no attribute 'num_gpus'

### ISSUE THREAD

**Issue by moshengmao** [jsvir/vad#1]
/nemo/utils/exp_manager.py", line 232, in exp_manager
    global_rank = trainer.node_rank * trainer.num_gpus + local_rank
AttributeError: 'Trainer' object has no attribute 'num_gpus'

**Comment by moshengmao** [comment]
/nemo/utils/exp_manager.py", line 232, in exp_manager
    global_rank = trainer.node_rank * trainer.num_gpus + local_rank
AttributeError: 'Trainer' object has no attribute 'num_gpus'

**Comment by jsvir** [comment]
Hi, the reason is a different version of pytorch-lightning. Which ptl version do you use?

**Comment by moshengmao** [comment]
I change “global_rank = trainer.node_rank * trainer.num_gpus + local_rank” into “global_rank = trainer.node_rank * trainer.num_nodes + local_rank”，and my pytorch-lightning  version is 1.9.4

**Comment by moshengmao** [comment]
If I want to use your dataset in the paper"We split the segments to the maximal length of 0.63 seconds and added them as an additional category to the Speech Google Commands V2 dataset.", and I download Freesound and GSCV2 dataset, how to mix the two datasets, I want to try.

**Comment by moshengmao** [comment]
Also, "We publish a pre-trained Pytorch checkpoint (sgvad.pth)", I use my own dataset to train , the project generates .ckpt , but the inference file"sgvad.py" use the ".ckpt"file, there is bug"

> Traceback (most recent call last):
>   File "/SG-vad-main/sgvad.py", line 89, in <module>
>     sgvad = SGVAD.init_from_ckpt()
>   File "/SG-vad-main/sgvad.py", line 73, in init_from_ckpt
>     preprocessor.load_state_dict(ckpt['preprocessor'], strict=True)
> KeyError: 'preprocessor'"

and I print the outputs of .pth and .ckpt,respectively,  I found the context of the two files is similar, but the orderdict is different. The output of sgvad.pth is"

> preprocessor OrderedDict([('featurizer.dct_mat', tensor()xxxxxxx

",and the output of SG-VAD--val_loss=2.9956-epoch=102.ckpt is “

> ckpt {'preprocessor': OrderedDict([('featurizer.dct_mat', tensor([[ 0.1768,  0.24

”.
Maybe I should change .ckpt into .pth?
Maybe I should try the function in the sgvad.py?
 `def save_ckpt(self):
        ckpt_dict = {"preprocessor": self.preprocessor.state_dict(), "vad": self.model.state_dict()}
        torch.save(ckpt_dict, './sgvad.pth')
   `     
I did't see the call of the "save_ckpt".

**Comment by moshengmao** [comment]
Forgive me , I have too many questions. Your threshold is 3.5, is this loss? And how to choose the threshold. Thank you!

**Comment by jsvir** [comment]
Hello @moshengmao,

Sorry for the delay in my response.
Once the model is trained (SG-VAD module + auxiliary classifier module), we calculate the model prediction score by summing up the tensor in channel dimension and taking a mean value in time dimension. So the score is the prediction confidence. It is not normalized to the range [0,1] and your target data examples should be used for setting the optimal score for your application.
If you define the score to be 2.0 then you will probably accept many noise chunks in addition to the speech chunks.
We recommend to set the value to be [3,3.5] but you should verify on your target audios that it is good enough.

Please ask any questions you have. 

Best

**Comment by jsvir** [comment]
> Also, "We publish a pre-trained Pytorch checkpoint (sgvad.pth)", I use my own dataset to train , the project generates .ckpt , but the inference file"sgvad.py" use the ".ckpt"file, there is bug"
> 
> > Traceback (most recent call last):
> > File "/SG-vad-main/sgvad.py", line 89, in 
> > sgvad = SGVAD.init_from_ckpt()
> > File "/SG-vad-main/sgvad.py", line 73, in init_from_ckpt
> > preprocessor.load_state_dict(ckpt['preprocessor'], strict=True)
> > KeyError: 'preprocessor'"
> 
> and I print the outputs of .pth and .ckpt,respectively, I found the context of the two files is similar, but the orderdict is different. The output of sgvad.pth is"
> 
> > preprocessor OrderedDict([('featurizer.dct_mat', tensor()xxxxxxx
> 
> ",and the output of SG-VAD--val_loss=2.9956-epoch=102.ckpt is “
> 
> > ckpt {'preprocessor': OrderedDict([('featurizer.dct_mat', tensor([[ 0.1768,  0.24
> 
> ”. Maybe I should change .ckpt into .pth? Maybe I should try the function in the sgvad.py? `def save_ckpt(self): ckpt_dict = {"preprocessor": self.preprocessor.state_dict(), "vad": self.model.state_dict()} torch.save(ckpt_dict, './sgvad.pth') ` I did't see the call of the "save_ckpt".

Regarding the checkpoin: the NeMo model is saved as a standard pytorch-lightning checkpoint. In order to produce the model in the format we put here on the Github we use the function [here ](https://github.com/jsvir/vad/blob/d57faefc5fdd01a4fba694acd64c0a05f7599aba/sgvad.py#L50C7-L50C7) that operates on the NeMo model. To convert the model you can use the next code:

```  train_cfg= OmegaConf.load("train_cfg.yaml")
    nemo_ckpt_path = "Classifier-with-STG-VAD--val_loss=0.0398-epoch=98.ckpt" # for example
    nemo_model = EncDecClassificationModel(cfg=train_cfg.model)
    ckpt = torch.load(nemo_ckpt_path , map_location='cpu')
    nemo_model .load_state_dict(ckpt['state_dict'], strict=False)

    print("Saving SGVAD as a seperate model")
    sgvad_dict = {'ckpt': nemo_model.fs.state_dict(), 'cfg': train_cfg.model.feature_selector}
    torch.save(sgvad_dict , './sg-vad.pth')

    print("Saving preprocessor as a seperate model")
    prep_dict = {'ckpt': nemo_model.preprocessor.state_dict(), 'cfg': train_cfg.model.preprocessor}
    torch.save(prep_dict, './preprocessor.pth') 
```
