### ISSUE TITLE
How to train the model？My labels seems wrong

### ISSUE THREAD

**Issue by moshengmao** [jsvir/vad#2]
The labels should be the context of the words,right?
If my labels are "thunderstorm""crying baby", the training results are bad, the classifier don't work

**Comment by jsvir** [comment]
Hi @moshengmao ,

The labels should be in the same format is for Classification Models in NeMo. The only difference is that we add an additional label "background"  at the last place in the labels list in the config [here](https://github.com/jsvir/vad/blob/250d72845d6e1df3d7a83aebe2249534783e1fd6/train_cfg.yaml#L12).

Please follow the tutorial NeMo team prepared for speech commands dataset preparation:
https://github.com/NVIDIA/NeMo/blob/main/tutorials/asr/Speech_Commands.ipynb
