### ISSUE TITLE
What is the version of pytorch lightning?

### ISSUE THREAD

**Issue by enlunox** [jsvir/vad#3]
I set up the environment following the installation steps from NeMo.
But I met an error:
Traceback (most recent call last):
  File "vad/sgvad.py", line 4, in <module>
    from nemo.collections.asr.modules import AudioToMFCCPreprocessor, ConvASREncoder
  ...
  vad/nemo/collections/common/callbacks/callbacks.py", line 17, in <module>
    from pytorch_lightning.callbacks.base import Callback
ModuleNotFoundError: No module named 'pytorch_lightning.callbacks.base'

What is the version of pytorch lightning? Can you provide the requirements.txt or some information so I can reproduce your environment?
Thank you!

**Comment by jsvir** [comment]
Thank you for your suggestion, I've added a requirements file with basic packages I have in my environment. 
Please let me know if you have any additional issues.
