### ISSUE TITLE
Question of reg_loss 

### ISSUE THREAD

**Issue by hsiaohan0827** [jsvir/vad#4]
Thanks for sharing the code!
I've noticed the reg_loss term in training_step function. (https://github.com/jsvir/vad/blob/main/nemo/collections/asr/models/classification_models.py#L525)
Does this loss correspond to the SG loss (L_sg) in paper, as shown in section 2.2?

**Comment by jsvir** [comment]
Yes, this is the L_sg term which is regularization term that closes the gates
